- repo_mining/Joshua_CollectFiles.py
- repo_mining/Joshua_authorsFileTouches.py
Added CollectFiles and authorsFileTouches as I forgot to add them originally to my first PR
> Added CollectFiles and authorsFileTouches. Forgot to add them

- test_coverage_lab/tests/test_account.py
Added a positive deposit test to see if the deposit function is working
> Added positive deposit test

- test_coverage_lab/tests/test_account.py
this test case tests the deactivation and reactivation of accounts
the line of code in models/account.py covered is specifically line 23 (disabled attribute of account)
> add test cases for account deactivation and reactivation

- tdd_lab/tests/test_counter.py
Added a test case to make sure that trying to increment a counter that does not exist returns a 404 not found error
from lines 73-78
> Student 6 non-existing counter

- workflows/ci.yml
Added initial GitHub Actions workflow
> Ci yaml file to workflows

- ci_lab/tests/test_counter.py
Checks if counter are sorted correctly
> Added assertion to student 2

- ci_lab/tests/test_counter.py
This pull request adds the missing assertions for student 5. The additional assertions verify that the error message for a negative number is correct, and also that setting a counter to a value of zero works properly.
> Added missing assertion for Student 5 test case

- ci_lab/tests/test_counter.py
- adding the missing assertion for 'bottom N counters' test case
- ensuring that the counter is correctly included in the response
- verified that the test passes in local pytest runs
> adding missing assertion for bottom N counters test case

- ci_lab/tests/test_counter.py
- fixing the comment to say "Test: Retrieve bottom N lowest counters" instead of "Test: Retrieve top N lowest counters"
> fixing comment title for test case student 3 

- .idea/.gitignore
- .idea/Group-1.iml
- .idea/inspectionProfiles/profiles_settings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- ci_lab/tests/test_counter.py
Added missing assertion for Student 7 test case
> my commit ci lab

- .idea/.gitignore
- .idea/Group-1.iml
- .idea/inspectionProfiles/profiles_settings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- ci_lab/tests/test_counter.py
> Add test assertion

- gen_ai/task2.1/Jordan_refactor_code.py
Task 2.1 solved issue Task 2.1
> Refactored code

- gen_ai/task2.2/Jordan_docstring_update.py
Closes issue task 2.2 tic tac toe
> Task 2.2 Jordan

- gen_ai/task2.1/Evan_refactor_code.py
Fixes #76 
Areas of improvement:
Encapsulation & Organization
Removal of Global Variables
Improved Instruction Handling
Make execute() More Maintainable
Improve Error Handling & Input Validation
> Refactoring Code

- gen_ai/task2.1/matthew_refactor_code.py
https://chatgpt.com/share/67be9d37-09bc-8006-8068-8ec3dd00bd2e
Asked chat gpt to help improve the code readability and efficiency.
> Base 10 to base 7 improvements

- gen_ai/task2.2/matthew_docstring_update.py
https://chatgpt.com/share/67bea046-df8c-8006-b951-283f2e87fb6b
Asked chatGPT to help the documentation of the code
> Base 10 to base 7 documentation

- gen_ai/task2.2/matthew_docstring_update.py
- gen_ai/task2.3/matt_complex.py
https://chatgpt.com/share/67bea4e5-f83c-8006-9743-ea498778b72d
Asked chatgpt to help make the matrix function less complex
> Matt task2.3

- gen_ai/task2.1/Evan_refactor_code.py
- gen_ai/task2.2/Evan_docstring_update.py
- gen_ai/task2.3/Evan_simplified_code.py
Fixes #86 
Added clear documentation to the entire file
> Added Documentation

- gen_ai/task2.3/Evan_simplified_code.py
Fixes #88 
(Had to redo the commit as task 2.2 wasn't merged when I did the original commit for simplifying the code)
> Simplify Code

- .idea/.name
- gen_ai/task2.1/RubiE_refactor_code.py
This fixes issue #80 and the old code is commented out on the top with the github convo link in the middle and the new refactored code at the bottom
> Task 2.1 Pull Request

- gen_ai/task2.1/Maylees_refactor_code.cpp
Used an old 135 assignment and commented out the original code and have the refactored code as the active code.
> Task 2.1 Needing Improvement

- gen_ai/task2.2/RubiE_docstring_update.py
This will close out issue #98 and has the updated code with documentation at the bottom, old code at the top, and the github convo link in the middle
> Task 2.2 Pull Request

- gen_ai/task2.3/RubiE_complex_code.py
This should close out issue #100 and the code is updated at the bottom with chatgpt link in the middle and the old complex code at the top
> PR for task 2.3

- gen_ai/task2.1/Josh_refactor_code.py
This PR refactors the Tic-Tac-Toe game code to address several issues and improve code efficiency. The main changes include:
- Fixed Initial Board Display Issue: The board now correctly shows numbers 1-9 at the start of the game.
- Corrected Win/Tie Condition Logic: The game no longer declares a tie after a single move.
- Consolidated Player Input Functions: Combined `get_x_player_choice()` and `get_o_player_choice()` into `get_player_choice(symbol)` to reduce redundancy.
- Enhanced AI Move Selection: Improved computer opponent logic to prioritize better moves.
- General Code Cleanup: Refactored functions for improved readability and maintainability.
This refactor was conducted based on a ChatGPT-assisted review and feedback loop.
ChatGPT Discussion & Refactoring Process: [ChatGPT Link of …
> Refactor Tic-Tac-Toe Game Logic and Fix Board Display Issues

- gen_ai/task2.2/Josh_docstring_update.py
**Overview**:
This PR enhances the documentation for the Tic Tac Toe game by adding function docstrings and inline comments to improve code readability and maintainability.
**Changes Made**:
1. Added docstrings to all functions, describing their purpose, parameters, and return values.
2. included inline comments to clarify key logic in game flow, board updates, and win conditions.
3. improved code readability by ensuring proper formatting and spacing.
4. no changes to functionality – the game logic remains the same.
**References**:
- Closes #102
- Improvements were made based on ChatGPT's feedback and conversation
- [Link to ChatGPT conversation](https://chatgpt.com/share/67bee733-bd80-8013-8625-408c7e16b451)
**Testing**:
- Successfully ran the game after documentation updates to ensure …
> Improve Documentation for Tic Tac Toe Game: Added Docstrings & Comments

- gen_ai/task2.3/Jordan_complex_code.py
Make complex code better for shortest path
> Solved issue task 2.3

- gen_ai/task2.2/Brenda_docstring_update.cpp
- gen_ai/task2.3/Brenda_complex_code.cpp
Adding comments and improving documentation to my cs 135 code
> Task 2.2 Improving Documentation

- gen_ai/task2.3/Brenda_complex_code.cpp
Understanding my cs 460 complex code with the help of Chat GPT
> Task 2.3 Complex code

- gen_ai/task2.1/Jaydan_refactor_code.cpp
Refactored code segment using ChatGPT. Removed duplicate code by creating new functions
> Task 2.1, fix for issue #79

- gen_ai/task2.2/Jaydan_docstring_update.cpp
Added comments to file using ChatGPT to explain the code
> Task 2.2: Fix for issue #115, Jaydan_docstring_update.cpp documentation

- gen_ai/task2.2/Maylee_docstring_update.cpp
> 2.2 fixes issue #118

- gen_ai/task2.1/Maylees_refactor_code.cpp
> Task 2.1 fixes issue #117

- gen_ai/task2.3/Maylee_complex_code.cpp
Task 2.3 improving complex code #121 issue from lines 244 to 268.
> Task 2.3 improving complex code #121
